name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Hugoのgit情報取得に必要

      - name: Setup Hugo
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.157.0/hugo_extended_0.157.0_linux-amd64.deb
          sudo dpkg -i hugo_extended_0.157.0_linux-amd64.deb

      - name: Build
        run: hugo --cleanDestinationDir --minify

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STELLORBITNET }}
          channelId: live
          projectId: stellorbitnet